# Generated by Django 5.2.5 on 2025-09-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_generate_qr_codes'),
        ('products', '0002_product_qr_code'),
    ]

    operations = [
    ]
