# Generated by Django 5.2.5 on 2025-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_0002_generate_qr_codes_0002_product_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='on_time_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
